/* Generated by `cspr dev package sync`; do not edit by hand. */
export const REGISTERED_ACTION_IDS = ["image.generate", "animation.generate", "frame.redraw", "sheet.slice", "video.sample", "normal.generate", "sprite.pixelize", "image.views", "image.pixelize", "image.cutout"] as const;
export type RegisteredActionId = typeof REGISTERED_ACTION_IDS[number];
export const TOOL_PACKAGE_VERSIONS = {"bridge": "1.0.0", "frames": "1.0.0", "image": "1.0.0", "normal": "1.2.0", "pixel": "2.1.0"} as const;
