/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Actions */
        get: operations["actions_api_v1_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Action */
        get: operations["action_api_v1_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/{action_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Action Run */
        post: operations["start_action_run_api_v1_actions__action_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifacts */
        get: operations["artifacts_api_v1_artifacts_get"];
        put?: never;
        /** Upload Artifact */
        post: operations["upload_artifact_api_v1_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/gc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gc */
        post: operations["gc_api_v1_artifacts_gc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Artifact */
        patch: operations["patch_artifact_api_v1_artifacts__artifact_id__patch"];
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Content */
        get: operations["artifact_content_api_v1_artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Artifact */
        post: operations["restore_artifact_api_v1_artifacts__artifact_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/sequence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame Sequence */
        get: operations["get_frame_sequence_api_v1_artifacts__artifact_id__sequence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trash Artifact */
        post: operations["trash_artifact_api_v1_artifacts__artifact_id__trash_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bridge Download */
        get: operations["bridge_download_api_v1_bridge_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bridge Upload */
        post: operations["bridge_upload_api_v1_bridge_runs__run_id__artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comfyui/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Comfyui
         * @description Read a ComfyUI endpoint without managing its filesystem or process.
         */
        post: operations["probe_comfyui_api_v1_comfyui_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gallery */
        get: operations["gallery_api_v1_gallery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Artifacts */
        get: operations["project_artifacts_api_v1_projects__project_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_projects__project_id__document_get"];
        /** Put Document */
        put: operations["put_document_api_v1_projects__project_id__document_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Project */
        post: operations["export_project_api_v1_projects__project_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_projects__project_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Materialize Track Sequence
         * @description Turn the current curated track into the typed hand-off artifact.
         *
         *     This operation persists only a small ordered manifest. It performs no
         *     image processing and therefore stays on the CookSprite control plane.
         */
        post: operations["materialize_track_sequence_api_v1_projects__project_id__sequences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Run */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtimes */
        get: operations["runtimes_api_v1_runtimes_get"];
        put?: never;
        /** Create Runtime */
        post: operations["create_runtime_api_v1_runtimes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Runtime */
        delete: operations["delete_runtime_api_v1_runtimes__runtime_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Capabilities View */
        get: operations["runtime_capabilities_view_api_v1_runtimes__runtime_id__capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Defaults View */
        get: operations["runtime_defaults_view_api_v1_runtimes__runtime_id__defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/defaults/normal/{mode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Runtime Normal Estimator */
        put: operations["set_runtime_normal_estimator_api_v1_runtimes__runtime_id__defaults_normal__mode__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/defaults/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Runtime Default */
        put: operations["set_runtime_default_api_v1_runtimes__runtime_id__defaults__action_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/defaults/{action_id}/modes/{mode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Runtime Mode Default */
        put: operations["set_runtime_mode_default_api_v1_runtimes__runtime_id__defaults__action_id__modes__mode__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Doctor */
        post: operations["doctor_api_v1_runtimes__runtime_id__doctor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Recipe */
        post: operations["import_recipe_api_v1_runtimes__runtime_id__recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtimes/{runtime_id}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Runtime */
        post: operations["select_runtime_api_v1_runtimes__runtime_id__select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionControl */
        ActionControl: {
            /**
             * Advanced
             * @default false
             */
            advanced: boolean;
            /** Default */
            default?: unknown;
            /** I18N */
            i18n: {
                [key: string]: components["schemas"]["LocalizedText"];
            };
            /** Id */
            id: string;
            /** Max */
            max?: number | null;
            /** Min */
            min?: number | null;
            /** Options */
            options?: components["schemas"]["ActionOption"][];
            /** Options Range */
            options_range?: number[] | null;
            /** Step */
            step?: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "select" | "multi-select" | "toggle" | "range" | "number" | "text" | "color" | "seed";
        };
        /** ActionDescriptor */
        ActionDescriptor: {
            /** Accepts */
            accepts?: {
                [key: string]: components["schemas"]["ActionInput"];
            };
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Controls */
            controls?: components["schemas"]["ActionControl"][];
            /** I18N */
            i18n: {
                [key: string]: components["schemas"]["LocalizedText"];
            };
            /** Id */
            id: string;
            /** Models */
            models?: components["schemas"]["ModelOption"][];
            /**
             * Presentation
             * @default generic
             */
            presentation: string;
            /** Produces */
            produces: ("Image" | "ImageBatch" | "SpriteSheet" | "FrameSeq" | "Video" | "Mask" | "NormalMap" | "NormalMapSequence" | "PixelGeometryPlan" | "Palette" | "SpritePair" | "CookSpritePack")[];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /** ActionInput */
        ActionInput: {
            /**
             * Max
             * @default 1
             */
            max: number;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Type */
            type: ("Image" | "ImageBatch" | "SpriteSheet" | "FrameSeq" | "Video" | "Mask" | "NormalMap" | "NormalMapSequence" | "PixelGeometryPlan" | "Palette" | "SpritePair" | "CookSpritePack") | ("Image" | "ImageBatch" | "SpriteSheet" | "FrameSeq" | "Video" | "Mask" | "NormalMap" | "NormalMapSequence" | "PixelGeometryPlan" | "Palette" | "SpritePair" | "CookSpritePack")[];
        };
        /** ActionOption */
        ActionOption: {
            /** Categories */
            categories?: string[];
            example?: components["schemas"]["ArtifactRef"] | null;
            /** I18N */
            i18n: {
                [key: string]: components["schemas"]["LocalizedText"];
            };
            /** Id */
            id: string;
        };
        /** ActionRunCreate */
        ActionRunCreate: {
            /** Inputs */
            inputs?: {
                [key: string]: string | string[];
            };
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Project */
            project: string;
            /** Values */
            values?: {
                [key: string]: unknown;
            };
        };
        /** AnimationClip */
        AnimationClip: {
            /**
             * Action
             * @enum {string}
             */
            action: "idle" | "walk" | "run" | "attack" | "cast" | "hit" | "jump" | "death";
            /** Id */
            id: string;
            /**
             * Loop
             * @default linear
             * @enum {string}
             */
            loop: "none" | "linear" | "pingpong";
            /** Name */
            name: string;
            /** Views */
            views?: components["schemas"]["ViewTrack"][];
        };
        /** ArtifactPatch */
        ArtifactPatch: {
            /** Favorite */
            favorite?: boolean | null;
            /** Title */
            title?: string | null;
        };
        /**
         * ArtifactRef
         * @description The only public handle for persisted visual material.
         *
         *     UI surfaces receive this object rather than an untyped media URL.  The URL
         *     remains an implementation detail of the reference and is never sufficient
         *     on its own to participate in a CookSprite workflow.
         */
        ArtifactRef: {
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @default Image
             */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id?: string | null;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Trashed
             * @default false
             */
            trashed: boolean;
            /** Url */
            url: string;
        };
        /** CharacterDocument */
        CharacterDocument: {
            /** Clips */
            clips?: components["schemas"]["AnimationClip"][];
            pivot?: components["schemas"]["Pivot"];
        };
        /** ComfyProbeCreate */
        ComfyProbeCreate: {
            /** Base Url */
            base_url: string;
        };
        /** DirectionTrack */
        DirectionTrack: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw";
            /** Frames */
            frames?: components["schemas"]["FrameRef"][];
        };
        /** DocumentView */
        DocumentView: {
            document: components["schemas"]["SpriteDocument"];
            /** Etag */
            etag: string;
            /** Revision */
            revision: number;
        };
        /** FrameRef */
        FrameRef: {
            /** Artifact */
            artifact: string;
            /**
             * Duration Ms
             * @default 100
             */
            duration_ms: number;
            /** Id */
            id: string;
            /** Normal */
            normal?: string | null;
            /**
             * Offset X
             * @default 0
             */
            offset_x: number;
            /**
             * Offset Y
             * @default 0
             */
            offset_y: number;
            /** Source Artifact */
            source_artifact?: string | null;
            /** Variant Of */
            variant_of?: string | null;
        };
        /** FrameSequenceManifest */
        FrameSequenceManifest: {
            /** Action */
            action?: ("idle" | "walk" | "run" | "attack" | "cast" | "hit" | "jump" | "death") | null;
            /** Direction */
            direction?: ("n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw") | null;
            /** Frames */
            frames: string[];
            /**
             * Schema
             * @default cooksprite.frame-sequence/v1
             * @constant
             */
            schema: "cooksprite.frame-sequence/v1";
            temporal?: components["schemas"]["FrameSequenceTemporal"] | null;
            /** View */
            view?: ("level" | "top45") | null;
        };
        /**
         * FrameSequenceTemporal
         * @description Bounded provenance needed to choose a temporal pixel strategy.
         */
        FrameSequenceTemporal: {
            /** Sample Fps */
            sample_fps: number;
            /**
             * Source
             * @constant
             */
            source: "sampled_video";
        };
        /** FrameSequenceView */
        FrameSequenceView: {
            artifact: components["schemas"]["ArtifactRef"];
            /** Frames */
            frames: components["schemas"]["ArtifactRef"][];
            sequence: components["schemas"]["FrameSequenceManifest"];
        };
        /** GalleryItem */
        GalleryItem: {
            cover?: components["schemas"]["ArtifactRef"] | null;
            project: components["schemas"]["ProjectView"];
            /** Published At */
            published_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocalizedText */
        LocalizedText: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** ModelOption */
        ModelOption: {
            /** Family */
            family: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Model Id */
            model_id: string;
            /** Modes */
            modes?: string[];
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** Runtime Id */
            runtime_id: string;
        };
        /** Pivot */
        Pivot: {
            /**
             * X
             * @default 0.5
             */
            x: number;
            /**
             * Y
             * @default 1
             */
            y: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Type
             * @default static
             * @enum {string}
             */
            type: "static" | "character" | "tileset";
        };
        /** ProjectExportCreate */
        ProjectExportCreate: {
            /**
             * Allow Incomplete
             * @default false
             */
            allow_incomplete: boolean;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Favorite */
            favorite?: boolean | null;
            /** Name */
            name?: string | null;
            /** Type */
            type?: ("static" | "character" | "tileset") | null;
        };
        /** ProjectView */
        ProjectView: {
            /** Cover Artifact Id */
            cover_artifact_id?: string | null;
            /** Created At */
            created_at: string;
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Published
             * @default false
             */
            published: boolean;
            /**
             * Type
             * @enum {string}
             */
            type: "static" | "character" | "tileset";
            /** Updated At */
            updated_at: string;
        };
        /** PublishCreate */
        PublishCreate: {
            /** Cover Artifact Id */
            cover_artifact_id?: string | null;
        };
        /** RecipeCreate */
        RecipeCreate: {
            /** Actions */
            actions: string[];
            /** Checkpoint */
            checkpoint?: string | null;
            /**
             * Family
             * @default comfy.imported
             */
            family: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Modes */
            modes: string[];
            /** Output */
            output: unknown[];
            /**
             * Output Name
             * @default image
             */
            output_name: string;
            /**
             * Output Type
             * @default Image
             */
            output_type: string;
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** Slot Types */
            slot_types?: {
                [key: string]: string;
            };
            /** Slots */
            slots: {
                [key: string]: string;
            };
            /** Workflow */
            workflow: {
                [key: string]: unknown;
            };
        };
        /**
         * RunRuntimeState
         * @description The provider-neutral live execution state shown by Web and CLI clients.
         */
        RunRuntimeState: {
            /**
             * Cached Nodes
             * @default 0
             */
            cached_nodes: number;
            /**
             * Completed Nodes
             * @default 0
             */
            completed_nodes: number;
            current?: components["schemas"]["RuntimeNodeView"] | null;
            error?: components["schemas"]["RuntimeErrorView"] | null;
            /**
             * Event
             * @default queued
             */
            event: string;
            /**
             * Message
             * @default queued
             */
            message: string;
            /**
             * Model Status
             * @default unknown
             * @enum {string}
             */
            model_status: "unknown" | "loading" | "ready" | "failed";
            /**
             * Phase
             * @default queued
             * @enum {string}
             */
            phase: "queued" | "starting" | "loading_model" | "sampling" | "processing" | "saving" | "completed" | "failed" | "cancelled" | "unknown";
            /** Queue Remaining */
            queue_remaining?: number | null;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** RunView */
        RunView: {
            /** Action Id */
            action_id?: string | null;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactRef"][];
            /**
             * Created At
             * @default
             */
            created_at: string;
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Project Id */
            project_id?: string | null;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /** Runtime Id */
            runtime_id?: string | null;
            /** Runtime Snapshot */
            runtime_snapshot?: string | null;
            runtime_state?: components["schemas"]["RunRuntimeState"];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancel_requested" | "cancelled" | "succeeded" | "failed";
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** RuntimeCreate */
        RuntimeCreate: {
            /** Base Url */
            base_url: string;
            /** Callback Url */
            callback_url?: string | null;
            /** Id */
            id?: string | null;
            /**
             * Label
             * @default ComfyUI
             */
            label: string;
            /**
             * Location
             * @default remote
             * @enum {string}
             */
            location: "local" | "remote";
            /**
             * Transport
             * @default http
             */
            transport: string;
            /**
             * Worker Managed
             * @default false
             */
            worker_managed: boolean;
        };
        /** RuntimeDefaultBinding */
        RuntimeDefaultBinding: {
            /** Model Id */
            model_id: string;
        };
        /** RuntimeErrorView */
        RuntimeErrorView: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Message */
            message: string;
            /** Node */
            node?: string | null;
            /** Type */
            type?: string | null;
        };
        /** RuntimeNodeView */
        RuntimeNodeView: {
            /**
             * Kind
             * @default other
             * @enum {string}
             */
            kind: "model" | "conditioning" | "sampling" | "processing" | "artifact" | "other";
            /** Label */
            label: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Status
             * @default executing
             * @enum {string}
             */
            status: "queued" | "executing" | "cached" | "completed" | "failed";
            /** Step */
            step?: number | null;
            /** Total */
            total?: number | null;
        };
        /** SpriteDocument */
        SpriteDocument: {
            /** Canvas */
            canvas?: {
                [key: string]: number;
            };
            character?: components["schemas"]["CharacterDocument"] | null;
            /**
             * Schema
             * @default cooksprite.sprite-document/v1
             * @constant
             */
            schema: "cooksprite.sprite-document/v1";
            static?: components["schemas"]["StaticDocument"] | null;
            tileset?: components["schemas"]["TileSetDocument"] | null;
            /**
             * Type
             * @enum {string}
             */
            type: "static" | "character" | "tileset";
        };
        /** StaticDocument */
        StaticDocument: {
            /** Normal */
            normal?: string | null;
            pivot?: components["schemas"]["Pivot"];
            /** Primary */
            primary?: string | null;
        };
        /** TileSetDocument */
        TileSetDocument: {
            /**
             * Exclude Empty
             * @default true
             */
            exclude_empty: boolean;
            /**
             * Margin
             * @default 0
             */
            margin: number;
            /** Normal */
            normal?: string | null;
            /** Source */
            source?: string | null;
            /**
             * Spacing
             * @default 0
             */
            spacing: number;
            /**
             * Tile Height
             * @default 32
             */
            tile_height: number;
            /**
             * Tile Width
             * @default 32
             */
            tile_width: number;
        };
        /**
         * TrackSequenceCreate
         * @description Materialize one curated SpriteDocument track as a reusable FrameSeq.
         */
        TrackSequenceCreate: {
            /**
             * Action
             * @enum {string}
             */
            action: "idle" | "walk" | "run" | "attack" | "cast" | "hit" | "jump" | "death";
            /**
             * Direction
             * @enum {string}
             */
            direction: "n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw";
            /**
             * View
             * @enum {string}
             */
            view: "level" | "top45";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViewTrack */
        ViewTrack: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Id
             * @enum {string}
             */
            id: "level" | "top45";
            /** Tracks */
            tracks?: components["schemas"]["DirectionTrack"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    actions_api_v1_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDescriptor"][];
                };
            };
        };
    };
    action_api_v1_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDescriptor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_action_run_api_v1_actions__action_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifacts_api_v1_artifacts_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                kind?: string | null;
                trashed?: boolean;
                search?: string;
                include_system?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_artifact_api_v1_artifacts_post: {
        parameters: {
            query?: {
                media_type?: string;
                kind?: string;
                project_id?: string | null;
                title?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gc_api_v1_artifacts_gc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_artifact_api_v1_artifacts__artifact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_content_api_v1_artifacts__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_artifact_api_v1_artifacts__artifact_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_sequence_api_v1_artifacts__artifact_id__sequence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameSequenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trash_artifact_api_v1_artifacts__artifact_id__trash_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bridge_download_api_v1_bridge_artifacts__artifact_id__get: {
        parameters: {
            query: {
                run_id: string;
                expires: number;
                signature: string;
                expand?: string;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bridge_upload_api_v1_bridge_runs__run_id__artifacts_post: {
        parameters: {
            query?: {
                kind?: string;
                source_artifact?: string;
                expires?: number;
                signature?: string;
                output_index?: number | null;
                canvas_width?: number | null;
                canvas_height?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_comfyui_api_v1_comfyui_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComfyProbeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gallery_api_v1_gallery_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryItem"][];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_artifacts_api_v1_projects__project_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_projects__project_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_document_api_v1_projects__project_id__document_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpriteDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_v1_projects__project_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectExportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_projects__project_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    materialize_track_sequence_api_v1_projects__project_id__sequences_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackSequenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameSequenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_api_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtimes_api_v1_runtimes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_runtime_api_v1_runtimes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_runtime_api_v1_runtimes__runtime_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_capabilities_view_api_v1_runtimes__runtime_id__capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_defaults_view_api_v1_runtimes__runtime_id__defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_runtime_normal_estimator_api_v1_runtimes__runtime_id__defaults_normal__mode__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
                mode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeDefaultBinding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_runtime_default_api_v1_runtimes__runtime_id__defaults__action_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeDefaultBinding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_runtime_mode_default_api_v1_runtimes__runtime_id__defaults__action_id__modes__mode__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
                action_id: string;
                mode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeDefaultBinding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    doctor_api_v1_runtimes__runtime_id__doctor_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_recipe_api_v1_runtimes__runtime_id__recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_runtime_api_v1_runtimes__runtime_id__select_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
